%YAML:1.0
---
image_width: 752
image_height: 480
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 458.654, 0., 367.215, 0.,
       457.296, 248.375, 0., 0., 1. ]
distortion_coefficients: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ -0.28340811, 0.07395907, 0.00019359, 1.76187114e-05, 0 ]